const COUNT_CHANGE = 'COUNT_CHANGE'
const STUDY_UPDATE = 'STUDY_UPDATE'
const GET_QQ_MUSIC = 'GET_QQ_MUSIC'

// 管理系统开发用到的
const FETCH_LOGIN = 'FETCH_LOGIN'
const FETCH_USER_INFO = 'FETCH_USER_INFO'
const LOGOUT_SUBMIT = 'LOGOUT_SUBMIT'

// 文章管理模块
const GET_ARTICLE = 'GET_ARTICLE'
const WRITE_ARTICLE_DONE = 'WRITE_ARTICLE_DONE'
const GET_ARTICLE_CATES = 'GET_ARTICLE_CATES'
const GET_ARTICLE_INFO = 'GET_ARTICLE_INFO'

export default {
	COUNT_CHANGE,
	STUDY_UPDATE,
	GET_QQ_MUSIC,
	FETCH_LOGIN,
	FETCH_USER_INFO,
	LOGOUT_SUBMIT,
	GET_ARTICLE,
	WRITE_ARTICLE_DONE,
	GET_ARTICLE_CATES,
	GET_ARTICLE_INFO
}
